### ISSUE TITLE
NatDeviceNotFoundException Problem

### ISSUE THREAD

**Issue by UmutComlekci** [lontivero/Open.NAT#41]
Hello,

I want to use this library in my app. But ConsoleTest app is sometimes found NAT device, most of times isn't found. What could cause of this?

**Comment by lontivero** [comment]
I need more information. Please, downlaod and run the **Open.Nat.ConsoleTest** console application and share the network.log file here.

**Comment by UmutComlekci** [comment]
I run the Open.Nat.ConsoleTest but I couldn't found network.log file.

For information:
When I start to app, most of times **Test().Wait();** method throw an NatDeviceNotFound exception. But sometimes (without any change of code), it's found the device and shown me my computer Public IP. That is the my problem.

Question 2 : I want to connect of IPAddress created by **device.GetExternalIPAsync()** method. But I cannot listen that IP with MappedPort. What's the solution of that problem? I check the port from canyouseeme.org and it's seems like closed.

I'm really appreciative to you. Thanks for answer and Open.NAT... Have a good day, good works

**Comment by lontivero** [comment]
@UmutComlekci the log file is in the same folder than the binary (.exe file). Tipically, if you run the app as it is, .\bin\debug or .\bin\release.

I need the info in that log in order to know what is really happening. Please, run it once more, review the log (and remove data that you don't want to share) and paste it here.

About your second question, you have to create a mapping as follow:
Just imagine you want to host a server in your personal computer (say, ip 192.168.0.1) listening on local port 80, this is, you want to have an application hosted on the [192.168.0.1:80] endpoint. However, 192.168.0.1 is a private ip and cannot be reached from internet, the only machine that can be reached in you network is your router. Say your router's public ip address is 203.71.54.102. What you have to do is to say your router: "wahtever traffic reachs you on port 80, send it to 192.168.0.1:80". And that's what Open.NAT is for. 

Next, you have to do 2 things:

1. set an application for listening on port 80
2. use canyouseeme.org for verifying that 203.71.54.102:80 is opened

**Comment by lontivero** [comment]
duplicated (see https://github.com/lontivero/Open.NAT/issues/34)
