### ISSUE TITLE
Dependency on TaskParallelLibrary is unneeded

### ISSUE THREAD

**Issue by bartwe** [lontivero/Open.NAT#44]
The dependency on the TaskParallelLibrary is unused on the 4.5 version and can be removed.

**Comment by lontivero** [comment]
@bartwe the TaskParallelLibrary is unused on the 4.5 and it is not referenced neither (I know VS lists it as a missing reference).

In the project file you can see the following reference element with a condition:

```
	<Reference Include="System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"
		 Condition="'$(Configuration)|$(Platform)' == 'Release 3.5|AnyCPU' OR '$(Configuration)|$(Platform)' == 'Debug 3.5|AnyCPU'">
      <HintPath>..\packages\TaskParallelLibrary.1.0.2856.0\lib\Net35\System.Threading.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

Anyway, to be sure the assembly is not referenced we can use ILSpy that show us the references in both, the 4.5 version and the 3.5 version:

![image](https://cloud.githubusercontent.com/assets/127973/17267651/1282eeb8-55e5-11e6-9100-ce286600b32e.png)

If I am right the real problem is that VS shows the reference and that's weird but the alternative is to maintain two projects (Open.Nat3.5 and Open.Nat4.5) that i don't like much.

If you know a better alternative please share it and i will consider it.

Thank you.

**Comment by bartwe** [comment]
Ah ok, feel free to close this bug.
